### ISSUE TITLE
CircleCI is broken

### ISSUE THREAD

**Issue by vsbogd** [singnet/atomspace#108]
`opencog` build fails on `Persisting to workspace` step with message:
```
The specified paths did not match any files in /ws
```
It happens in `atomspace` CircleCI pipeline only. 
Example https://circleci.com/gh/singnet/atomspace/445?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Related fix: https://github.com/opencog/opencog/pull/3591

**Comment by AmeBel** [comment]
`The specified paths did not match any files in /ws` is caused because ccache is not creating it. I don't know why.

**Comment by vsbogd** [comment]
One of the guess we have is after upgrading `opencog-deps` to ubuntu-18.04 ccache doesn't work anymore. @stellarspot, do you have updates on this?
