### ISSUE TITLE
GroundedSchema/Predicate implementation in "lib:"

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/atomspace#15]
"lib:" prefix for GroundedSchemaNode was originally designed to execute functions in dynamic libraries compiled from Haskell code. There is actually no rule that this should be necessarily a Haskell-based library, but not e.g. C++ library. Also, this functionality can be reused for executing local C++ functions not loaded from any library as was done [here](https://github.com/singnet/atomspace/pull/14).
However, the problem is that LibraryManager requires functions returning Handle*, not Handle, and memory allocated for this pointer is not released, but its content is copied (`result = *func(as, &args);` in ExecutionOutputLink.cc). Apparently, if GroundedSchema function will allocate memory for this pointer, it will not be freed. Thus, this line of code should be fixed, e.g.:
```
		Handle* res = func(as, &args);
		result = *res;
		free(res);
```
I've checked that freeing memory of this pointer doesn't cause a segmentation fault in Haskell code, so it seems like currently there is also a memory leakage in the case of Haskell also (although I'm not absolutely sure, and a more complex test is needed).
If `free` is added then the example [here](https://github.com/singnet/atomspace/pull/14#issuecomment-421274322) will not work properly, and the line
`return const_cast<Handle*>(&(params->atom_ptr()->getOutgoingSet()[0]));`
should be modified to: `return new Handle(params->atom_ptr()->getOutgoingSet()[0]);`
This variant is more preferable with the current interface, because it will allow creation of new atoms - not just returning pointers to existing Handle.
So, there are several possible solutions:
* keep the current interface for all compiled functions, add `free`, and allocate memory for Handle* in GroundedSchema functions;
* keep Haskell interface as it is now (with possible memory leakage) and create a separate interface for local functions and C++ libraries, which will assume that GroundedSchema functions return Handle instead of Handle*
* do nothing

**Comment by vsbogd** [comment]
I would say we should either fix the memory leak in Haskell API or stop supporting this API at all.
Quick look at Haskell/C interference API shown that to pass smart pointer via Haskell API one need reimplement some kind of C++ smart pointer structure in Haskell. This is the reason probably why Haskell API implementation returns pointers.

I think to have better API for C++ is a good idea. An may be in future we can migrate Haskell to this API using some sort of C++/Haskell code generator (I have found one such project using google).

**Comment by ngeiswei** [comment]
I didn't look into this in details but adding free seems like the simplest thing to do. I wonder if @rTreutlien has something to say about it.

**Comment by vsbogd** [comment]
agree

**Comment by Necr0x0Der** [comment]
One "problem" is that GroundedPredicate API for Haskell is absent. `EvaluationLink::do_evaluate` simply contains a copy of the switched-off code from `do_execute`, which cannot work for `do_evaluate` because it assumes that Handle* is returned - not TruthValuePtr. If we dig into Haskell binding code, we can see that there is Haskell own types for different TruthValues, and there is C++ and Haskell code for converting a vector of doubles to C++ TruthValue and to Haskell TruthValue. E.g. in Internal.hs there is `toTVRaw` and `fromTVRaw` where TVRaw is a vector of doubles. Also, TruthValue_CWrapper.cpp contains `TruthValue_getFromAtom` and `TruthValue_setOnAtom` which sets and gets TVRaw from/to atoms. Apparently, there is no API for returning C++ TruthValuePtr from Haskell code! That's why GroundedPredicates in Haskell are not implemented. This can actually be easily solved by introducing a new function in TruthValue_CWrapper.cpp, which will return a pointer to `TruthValuePtr` created from TVRaw in a similar way as done in `TruthValue_setOnAtom` (actually, these two functions can use the same code); then external TruthValuePtr* type can be introduced in Haskell (with the only purpose to be returned by Haskell grounded predicates in similar way as Handle* is returned by grounded schemas).
I'm not sure I'm going to implement this for Haskell by myself, but my point is that "lib:" API for GroundedPredicates can assume that external functions has signature `TruthValuePtr* func(AtomSpace *, Handle*)`, which I was initially intended to add for C++ grounded predicates, but wasn't sure that it would be reusable by Haskell (and now I'm almost certain that it will not only be reusable, but this is a natural way to add missing Haskell functionality).

**Comment by Necr0x0Der** [comment]
@vsbogd , @ngeiswei , do you think I should fix `do_execute` and add a unit test for C++ grounding functions separately from reanimating GroundedPredicate "lib:" API, which should be raised as an independent issue?

**Comment by vsbogd** [comment]
I think yes, it makes sense. We can create separate issue for GroundedPredicate and fix memory leak under this issue.

**Comment by Necr0x0Der** [comment]
It seems that we can close this issue and move on to the [next one](https://github.com/singnet/atomspace/issues/18)
