### ISSUE TITLE
GroundedPredicate "lib:" interface is absent

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/atomspace#18]
Few questions:
* is it OK for grounding functions for "lib:" GroundedPredicate to have a signature `TruthValuePtr* func(AtomSpace *, Handle*)`?
* LibraryManager is implemented in ExecutionOutputLink.cc; should EvaluationLink.cc use the same LibraryManager? If yes, should it be moved to a separate file or kept in ExecutionOutputLink.cc ?
* Should "lib:" GroundedPredicate and GroundedSchema be both stored in the same `std::unordered_map<std::string, void*> LibraryManager::_functions;` or is it better to separate it into `std::unordered_map<std::string, void*> LibraryManager::_schemas;` and `std::unordered_map<std::string, void*> LibraryManager::_predicates;`?

**Comment by ngeiswei** [comment]
> is it OK for grounding functions for "lib:" GroundedPredicate to have a signature `TruthValuePtr* func(AtomSpace *, Handle*)`?

I would say yes, out of cohesiveness.

> LibraryManager is implemented in ExecutionOutputLink.cc; should EvaluationLink.cc use the same LibraryManager? If yes, should it be moved to a separate file or kept in ExecutionOutputLink.cc ?

I'd move `LibraryManager` to a separate file, yes.

> Should "lib:" GroundedPredicate and GroundedSchema be both stored in the same `std::unordered_map<std::string, void*> LibraryManager::_functions;` or is it better to separate it into `std::unordered_map<std::string, void*> LibraryManager::_schemas;` and `std::unordered_map<std::string, void*> LibraryManager::_predicates;`?

Maybe better to separate them, but frankly I don't know.
