### ISSUE TITLE
Speed up Haskell compilation in circleci

### ISSUE THREAD

**Issue by ngeiswei** [singnet/atomspace#28]
Probably the biggest bottleneck (or should I say the smallest?) in the AtomSpace compilation in [circleci](https://circleci.com/gh/singnet/atomspace) is the Haskell part. Installing ghc alone takes a few minutes.

Maybe that process can be cached similarly to using ccache for C++. It looks like [Nix](https://github.com/Gabriel439/haskell-nix) could be a viable option.

**Comment by AmeBel** [comment]
Once I setup the build of separate images for testing and then the lost minutes will be saved.

**Comment by ngeiswei** [comment]
In case this may be useful https://github.com/yukiasai/haskell-circleci-example
