### ISSUE TITLE
add weakref support to atoms and truth values

### ISSUE THREAD

**Issue by noskill** [singnet/atomspace#87]
the issue is related to https://github.com/singnet/opencog/issues/70 - pytorch truth values.
In order to update stv value simultaneously with torch truth value it useful to store atom or stv in TTruthValue instance using weak reference.

https://docs.python.org/3/extending/newtypes.html#weakref-support

**Comment by noskill** [comment]
better to make torch truth value  a subclass of simple truth values

**Comment by vsbogd** [comment]
Better solution is to implement `TorchTruthValue` as subclass of `TruthValue`.
